/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Font;
import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;

import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import funcion.Aldea;
import funcion.Animal;
import funcion.Parcela;
import funcion.Personaje;
import funcion.TorreDefensa;

/**
 *
 * @author 23jic
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Aldea aldea;
    private final int LABEL_SIZE = 60;

    /**
     * Creates new form VentanaPrincipal2
     */
    public VentanaPrincipal(Aldea aldea) {
        this.aldea = aldea;
        initComponents();
    }


    public int getLABEL_SIZE() {
        return LABEL_SIZE;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void actualizarRecursos(){
        labelVarCicloActual.setText(aldea.getCicloActual() + "");
        labelVarPersonajesVivos.setText(aldea.getPersonajes().size() + "");
        labelVarMaderaDisponible.setText(aldea.getMaderaDisponible() + "");
        labelVarCercaPrincipal.setText(aldea.getCercaPrincipal().getResistenciaActual() + "");
        labelVarComidaVegetal.setText(aldea.getComidaVegetalDisponible() + "");
        labelVarComidaAnimal.setText(aldea.getComidaAnimalDisponible() + "");
        labelVarAnimalesActivos.setText(aldea.getAnimalesActivos().size() + "");
        labelVarTorres.setText(aldea.getTorres().size() + "");
        labelVarParcelas.setText(aldea.getParcelasCultivo().size() + "");
        labelVarArbolesDisponibles.setText(aldea.getArbolesDisponibles() + "");
        labelVarTurnosSinComida.setText(aldea.getTurnosSinComida() + "");
    }

   public void actualizarLabel(javax.swing.JLabel label, String texto){
    label.setText(texto);
   }

   public void mostrarMensaje(boolean victoria){
    if (victoria){
        JOptionPane.showMessageDialog(this, "Victoria!");
    }
    else{
        JOptionPane.showMessageDialog(this, "Derrota!", "Derrota", JOptionPane.ERROR_MESSAGE);
    }
    //this.dispose();
    aldea.terminarSimulacion();
   }

    public void crearLabelsIniciales(){
        
        for (Personaje p : aldea.getPersonajes()){
            crearLabelPersonaje(p);
        }
        for (TorreDefensa t : aldea.getTorres()){
            crearLabelTorre(t);
        }
        for (Parcela parcela : aldea.getParcelasCultivo()){
            crearLabelParcela(parcela);
        }
        crearLabelCerca();
    }
    
    public void eliminarLabel(javax.swing.JLabel label){
        mainPanel.remove(label);
        mainPanel.repaint();
    }

    public void eliminarLabel(Point posicion){
        try {
            javax.swing.JLabel label = (javax.swing.JLabel) mainPanel.getComponentAt(posicion);
            if (label != null) {
                mainPanel.remove(label);
                mainPanel.repaint();
            }
            }
        catch (Exception e) {
            System.out.println("No se pudo eliminar el label en la posición: " + posicion);
        }
    }

    public void crearLabelPersonaje(Personaje personaje){
        ImageIcon icon = null;
        try {
            BufferedImage img = ImageIO.read(new File(personaje.getPathDefault()));
            Image dimg = img.getScaledInstance(getLABEL_SIZE(), getLABEL_SIZE(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(dimg);
        } catch (Exception e) {
            System.out.println("Error cargando imagen");
        }
        javax.swing.JLabel nuevoLabel = new javax.swing.JLabel(icon);
        mainPanel.add(nuevoLabel);
        personaje.setLabelGUI(nuevoLabel);
        nuevoLabel.setBackground(new java.awt.Color(200, 200, 200));
        nuevoLabel.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 12)); // NOI18N
        nuevoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setText(personaje.getNombre().substring(0, 2) + personaje.getNombre().substring(personaje.getNombre().length() - 1) );
        nuevoLabel.setIconTextGap(-15);
        nuevoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setOpaque(true);
        nuevoLabel.setBounds(LABEL_SIZE * aldea.getPersonajes().indexOf(personaje), 0, LABEL_SIZE, LABEL_SIZE);
        nuevoLabel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        personaje.setObjetivo(personaje.getLabelGUI().getLocation());
        mainPanel.setComponentZOrder(nuevoLabel, 0);
    }
    


    public void crearLabelTorre(TorreDefensa torre){
        ImageIcon icon = null;
        try {
            BufferedImage img = ImageIO.read(new File(torre.getPathDefault()));
            Image dimg = img.getScaledInstance(getLABEL_SIZE(), getLABEL_SIZE(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(dimg);
        } catch (Exception e) {
            System.out.println("Error cargando imagen");
        }
        javax.swing.JLabel nuevoLabel = new javax.swing.JLabel(icon);
        mainPanel.add(nuevoLabel);
        torre.setLabelGUI(nuevoLabel);
        //nuevoLabel.setBackground(new java.awt.Color(150, 150, 150));
        nuevoLabel.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 12));
        nuevoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setText(torre.getNombre().substring(0, 2) + torre.getNombre().substring(torre.getNombre().length() - 1) + "     ");
        nuevoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setIconTextGap(-15);
        nuevoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoLabel.setOpaque(true);
        nuevoLabel.setBounds(60*aldea.getTorres().indexOf(torre), LABEL_SIZE * 3, LABEL_SIZE, LABEL_SIZE);
        nuevoLabel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setComponentZOrder(nuevoLabel, 0);
    }
    
    public void crearLabelCerca(){
        ImageIcon icon = null;
        try {
            BufferedImage img = ImageIO.read(new File(aldea.getCercaPrincipal().getPathDefault()));
            Image dimg = img.getScaledInstance(getLABEL_SIZE() * 4, getLABEL_SIZE() * 4, Image.SCALE_SMOOTH);
            icon = new ImageIcon(dimg);
        } catch (Exception e) {
            System.out.println("Error cargando imagen");
        }
        javax.swing.JLabel nuevoLabel = new javax.swing.JLabel(icon);
        mainPanel.add(nuevoLabel);
        nuevoLabel.setBackground(new java.awt.Color(200, 100, 0));
        nuevoLabel.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 12));
        nuevoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setText("Cerca");
        nuevoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setIconTextGap(-15);
        nuevoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoLabel.setOpaque(true);
        nuevoLabel.setBounds(0, 0, LABEL_SIZE*4, LABEL_SIZE*4);
        nuevoLabel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        aldea.getCercaPrincipal().setLabelGUI(nuevoLabel);
    }

    public void crearLabelAnimal(Animal animal){
        ImageIcon icon = null;
        try {
            BufferedImage img = ImageIO.read(new File(animal.getPathDefault()));
            Image dimg = img.getScaledInstance(getLABEL_SIZE(), getLABEL_SIZE(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(dimg);
        } catch (Exception e) {
            System.out.println("Error cargando imagen");
        }
        javax.swing.JLabel nuevoLabel = new javax.swing.JLabel(icon);
        mainPanel.add(nuevoLabel);
        animal.setLabelGUI(nuevoLabel);
        //nuevoLabel.setBackground(new java.awt.Color(100, 200, 100));
        nuevoLabel.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 12));
        nuevoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setText(animal.getNombre().substring(0, 2) + animal.getNombre().substring(animal.getNombre().length() - 1) );
        nuevoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setIconTextGap(-15);
        nuevoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoLabel.setOpaque(true);
        nuevoLabel.setBounds(LABEL_SIZE * aldea.getAnimalesActivos().indexOf(animal), LABEL_SIZE * 5, LABEL_SIZE, LABEL_SIZE);
        nuevoLabel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setComponentZOrder(nuevoLabel, 0);
        animal.setObjetivo(nuevoLabel.getLocation());
    }

    public void crearLabelParcela(Parcela parcela){
        ImageIcon icon = null;
        try {
            BufferedImage img = ImageIO.read(new File(parcela.getPathDefault()));
            Image dimg = img.getScaledInstance(getLABEL_SIZE(), getLABEL_SIZE(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(dimg);
        } catch (Exception e) {
            System.out.println("Error cargando imagen");
        }
        javax.swing.JLabel nuevoLabel = new javax.swing.JLabel(icon);
        mainPanel.add(nuevoLabel);
        parcela.setLabelGUI(nuevoLabel);
        nuevoLabel.setBackground(new java.awt.Color(100, 100, 200));
        nuevoLabel.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 12));
        nuevoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setText(parcela.getNombre().substring(0, 1) + parcela.getNombre().substring(parcela.getNombre().length() - 1) + " T: " + parcela.getCiclosParaCosechar());
        nuevoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setIconTextGap(-15);
        nuevoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoLabel.setOpaque(true);
        nuevoLabel.setBounds(LABEL_SIZE * aldea.getParcelasCultivo().indexOf(parcela), LABEL_SIZE * 2, LABEL_SIZE, LABEL_SIZE);
        nuevoLabel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }

    public javax.swing.JLabel crearLabelArbol(ArrayList<Point> posicionesArboles){
        ImageIcon icon = null;
        try {
            BufferedImage img = ImageIO.read(new File(aldea.getPathArbol()));
            Image dimg = img.getScaledInstance(getLABEL_SIZE(), getLABEL_SIZE(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(dimg);
        } catch (Exception e) {
            System.out.println("Error cargando imagen");
        }
        
        javax.swing.JLabel nuevoLabel = new javax.swing.JLabel(icon);

        Collections.shuffle(posicionesArboles);
        nuevoLabel.setBounds(LABEL_SIZE * posicionesArboles.getFirst().x, LABEL_SIZE * posicionesArboles.getFirst().y, LABEL_SIZE, LABEL_SIZE);
        nuevoLabel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        
        //nuevoLabel.setIcon(img);
        mainPanel.add(nuevoLabel);
        mainPanel.setComponentZOrder(nuevoLabel, 0);
        return nuevoLabel;
    }

    public void habilitarAgregarPersonaje(){
        BtnAgregarPersonaje.setEnabled(true);
    }

    public void deshabilitarAgregarPersonaje(){
        BtnAgregarPersonaje.setEnabled(false);
    }
    
    public void moverPersonaje(Personaje p, int x, int y){
        p.getLabelGUI().setLocation(x, y);
        this.repaint();
    }

    public void moverAnimal(Animal animal, int x, int y){
        animal.getLabelGUI().setLocation(x, y);
        this.repaint();
    }

    public String obtenerPersonajeSeleccionado(){
        return ((String) comboBoxPersonaje.getSelectedItem());
    }

    public void agregarLog(String mensaje){
        jTextArea1.append(mensaje + "\n");
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelMaderaDisponible = new javax.swing.JLabel();
        labelVarMaderaDisponible = new javax.swing.JLabel();
        labelCercaPrincipal = new javax.swing.JLabel();
        labelVarCercaPrincipal = new javax.swing.JLabel();
        labelVarCicloActual = new javax.swing.JLabel();
        labelCicloActual = new javax.swing.JLabel();
        labelPersonajesVivos = new javax.swing.JLabel();
        labelVarPersonajesVivos = new javax.swing.JLabel();
        labelComidaVegetal = new javax.swing.JLabel();
        labelVarComidaVegetal = new javax.swing.JLabel();
        labelComidaAnimal = new javax.swing.JLabel();
        labelVarComidaAnimal = new javax.swing.JLabel();
        labelTorres = new javax.swing.JLabel();
        labelVarAnimalesActivos = new javax.swing.JLabel();
        labelAnimalesActivos = new javax.swing.JLabel();
        labelParcelas = new javax.swing.JLabel();
        labelVarTorres = new javax.swing.JLabel();
        labelVarParcelas = new javax.swing.JLabel();
        labelVarTurnosSinComida = new javax.swing.JLabel();
        labelTurnosSinComida = new javax.swing.JLabel();
        labelVarArbolesDisponibles = new javax.swing.JLabel();
        labelArbolesDisponibles = new javax.swing.JLabel();
        BtnAgregarPersonaje = new javax.swing.JButton();
        BtnAvanzarCiclo = new javax.swing.JButton();
        comboBoxPersonaje = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aldea Juego");
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setForeground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(51, 153, 0));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego Aldea");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        labelMaderaDisponible.setBackground(new java.awt.Color(0, 102, 51));
        labelMaderaDisponible.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMaderaDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaderaDisponible.setText("Madera disponible:");
        labelMaderaDisponible.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMaderaDisponible.setOpaque(true);

        labelVarMaderaDisponible.setBackground(new java.awt.Color(0, 102, 51));
        labelVarMaderaDisponible.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarMaderaDisponible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarMaderaDisponible.setText("Temp text");
        labelVarMaderaDisponible.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarMaderaDisponible.setOpaque(true);

        labelCercaPrincipal.setBackground(new java.awt.Color(0, 102, 51));
        labelCercaPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCercaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCercaPrincipal.setText("Cerca principal");
        labelCercaPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelCercaPrincipal.setOpaque(true);

        labelVarCercaPrincipal.setBackground(new java.awt.Color(0, 102, 51));
        labelVarCercaPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarCercaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarCercaPrincipal.setText("Temp text");
        labelVarCercaPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarCercaPrincipal.setOpaque(true);

        labelVarCicloActual.setBackground(new java.awt.Color(0, 102, 51));
        labelVarCicloActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarCicloActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarCicloActual.setText(aldea.getCicloActual() + "");
        labelVarCicloActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarCicloActual.setOpaque(true);

        labelCicloActual.setBackground(new java.awt.Color(0, 102, 51));
        labelCicloActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCicloActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCicloActual.setText("Ciclo Actual:");
        labelCicloActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelCicloActual.setOpaque(true);

        labelPersonajesVivos.setBackground(new java.awt.Color(0, 102, 51));
        labelPersonajesVivos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPersonajesVivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPersonajesVivos.setText("Personajes vivos:");
        labelPersonajesVivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelPersonajesVivos.setOpaque(true);

        labelVarPersonajesVivos.setBackground(new java.awt.Color(0, 102, 51));
        labelVarPersonajesVivos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarPersonajesVivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarPersonajesVivos.setText("Temp text");
        labelVarPersonajesVivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarPersonajesVivos.setOpaque(true);

        labelComidaVegetal.setBackground(new java.awt.Color(0, 102, 51));
        labelComidaVegetal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelComidaVegetal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelComidaVegetal.setText("Comida vegetal:");
        labelComidaVegetal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelComidaVegetal.setOpaque(true);

        labelVarComidaVegetal.setBackground(new java.awt.Color(0, 102, 51));
        labelVarComidaVegetal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarComidaVegetal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarComidaVegetal.setText("Temp text");
        labelVarComidaVegetal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarComidaVegetal.setOpaque(true);

        labelComidaAnimal.setBackground(new java.awt.Color(0, 102, 51));
        labelComidaAnimal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelComidaAnimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelComidaAnimal.setText("Comida animal:");
        labelComidaAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelComidaAnimal.setOpaque(true);

        labelVarComidaAnimal.setBackground(new java.awt.Color(0, 102, 51));
        labelVarComidaAnimal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarComidaAnimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarComidaAnimal.setText("Temp text");
        labelVarComidaAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarComidaAnimal.setOpaque(true);

        labelTorres.setBackground(new java.awt.Color(0, 102, 51));
        labelTorres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTorres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTorres.setText("Torres");
        labelTorres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTorres.setOpaque(true);

        labelVarAnimalesActivos.setBackground(new java.awt.Color(0, 102, 51));
        labelVarAnimalesActivos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarAnimalesActivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarAnimalesActivos.setText("Temp text");
        labelVarAnimalesActivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarAnimalesActivos.setOpaque(true);

        labelAnimalesActivos.setBackground(new java.awt.Color(0, 102, 51));
        labelAnimalesActivos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAnimalesActivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAnimalesActivos.setText("Animales activos");
        labelAnimalesActivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelAnimalesActivos.setOpaque(true);

        labelParcelas.setBackground(new java.awt.Color(0, 102, 51));
        labelParcelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelParcelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParcelas.setText("Parcelas");
        labelParcelas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelParcelas.setOpaque(true);

        labelVarTorres.setBackground(new java.awt.Color(0, 102, 51));
        labelVarTorres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarTorres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarTorres.setText("Temp text");
        labelVarTorres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarTorres.setOpaque(true);

        labelVarParcelas.setBackground(new java.awt.Color(0, 102, 51));
        labelVarParcelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarParcelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarParcelas.setText("Temp text");
        labelVarParcelas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarParcelas.setOpaque(true);

        labelVarTurnosSinComida.setBackground(new java.awt.Color(0, 102, 51));
        labelVarTurnosSinComida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarTurnosSinComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarTurnosSinComida.setText("Temp text");
        labelVarTurnosSinComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarTurnosSinComida.setOpaque(true);

        labelTurnosSinComida.setBackground(new java.awt.Color(0, 102, 51));
        labelTurnosSinComida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTurnosSinComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTurnosSinComida.setText("Turnos sin comida");
        labelTurnosSinComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTurnosSinComida.setOpaque(true);

        labelVarArbolesDisponibles.setBackground(new java.awt.Color(0, 102, 51));
        labelVarArbolesDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVarArbolesDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVarArbolesDisponibles.setText("Temp text");
        labelVarArbolesDisponibles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelVarArbolesDisponibles.setOpaque(true);

        labelArbolesDisponibles.setBackground(new java.awt.Color(0, 102, 51));
        labelArbolesDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelArbolesDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelArbolesDisponibles.setText("Árboles disponibles");
        labelArbolesDisponibles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelArbolesDisponibles.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labelMaderaDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarMaderaDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPersonajesVivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCicloActual, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVarCicloActual, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVarPersonajesVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelCercaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarCercaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelComidaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarComidaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelComidaVegetal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarComidaVegetal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelAnimalesActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarAnimalesActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelTorres, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarTorres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelArbolesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarArbolesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelTurnosSinComida, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVarTurnosSinComida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelTurnosSinComida)
                                        .addComponent(labelVarTurnosSinComida))
                                    .addGap(26, 26, 26))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelArbolesDisponibles)
                                        .addComponent(labelVarArbolesDisponibles))
                                    .addGap(52, 52, 52)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelCercaPrincipal)
                                .addComponent(labelVarCercaPrincipal)
                                .addComponent(labelAnimalesActivos)
                                .addComponent(labelVarAnimalesActivos)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelTorres)
                                    .addComponent(labelVarTorres))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelComidaVegetal)
                                    .addComponent(labelVarComidaVegetal)))
                            .addGap(26, 26, 26)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCicloActual)
                            .addComponent(labelVarCicloActual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPersonajesVivos)
                            .addComponent(labelVarPersonajesVivos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelParcelas)
                                    .addComponent(labelVarParcelas))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelComidaAnimal)
                                    .addComponent(labelVarComidaAnimal)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelMaderaDisponible)
                                .addComponent(labelVarMaderaDisponible))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        BtnAgregarPersonaje.setText("Agregar personaje");
        BtnAgregarPersonaje.setEnabled(false);
        BtnAgregarPersonaje.addActionListener(this::BtnAgregarPersonajeActionPerformed);

        BtnAvanzarCiclo.setText("Avanzar ciclo");
        BtnAvanzarCiclo.addActionListener(this::BtnAvanzarCicloActionPerformed);

        comboBoxPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automático", "Constructor", "Guardián", "Cazador", "Leñador", "Agricultor" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(BtnAvanzarCiclo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAgregarPersonaje)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAvanzarCiclo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(BtnAgregarPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAvanzarCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAvanzarCicloActionPerformed
        // TODO add your handling code here:
        BtnAvanzarCiclo.setEnabled(false);
        aldea.simularCiclo();
        BtnAvanzarCiclo.setEnabled(true);
    }//GEN-LAST:event_BtnAvanzarCicloActionPerformed

    private void BtnAgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarPersonajeActionPerformed
        // TODO add your handling code here:
        //Crear personaje
        aldea.agregarPersonaje(obtenerPersonajeSeleccionado());
    }//GEN-LAST:event_BtnAgregarPersonajeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarPersonaje;
    private javax.swing.JButton BtnAvanzarCiclo;
    private javax.swing.JComboBox<String> comboBoxPersonaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAnimalesActivos;
    private javax.swing.JLabel labelArbolesDisponibles;
    private javax.swing.JLabel labelCercaPrincipal;
    private javax.swing.JLabel labelCicloActual;
    private javax.swing.JLabel labelComidaAnimal;
    private javax.swing.JLabel labelComidaVegetal;
    private javax.swing.JLabel labelMaderaDisponible;
    private javax.swing.JLabel labelParcelas;
    private javax.swing.JLabel labelPersonajesVivos;
    private javax.swing.JLabel labelTorres;
    private javax.swing.JLabel labelTurnosSinComida;
    private javax.swing.JLabel labelVarAnimalesActivos;
    private javax.swing.JLabel labelVarArbolesDisponibles;
    private javax.swing.JLabel labelVarCercaPrincipal;
    private javax.swing.JLabel labelVarCicloActual;
    private javax.swing.JLabel labelVarComidaAnimal;
    private javax.swing.JLabel labelVarComidaVegetal;
    private javax.swing.JLabel labelVarMaderaDisponible;
    private javax.swing.JLabel labelVarParcelas;
    private javax.swing.JLabel labelVarPersonajesVivos;
    private javax.swing.JLabel labelVarTorres;
    private javax.swing.JLabel labelVarTurnosSinComida;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
